# Generated by Django 3.1 on 2020-09-02 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание')),
                ('parent1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Mom', to='main.cat')),
                ('parent2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Dad', to='main.cat')),
            ],
            options={
                'verbose_name': 'Кот',
                'verbose_name_plural': 'Коты',
            },
        ),
        migrations.CreateModel(
            name='Cat_Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('fk_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cat', verbose_name='Кот')),
            ],
            options={
                'verbose_name': 'Фото котов',
                'verbose_name_plural': 'Фото котов',
            },
        ),
    ]
