# Generated by Django 3.1 on 2020-09-08 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200908_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='sale',
            field=models.BooleanField(blank=True, null=True, verbose_name='На продажу?'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='parent1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Mom', to='main.cat', verbose_name='Мама'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='parent2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Dad', to='main.cat', verbose_name='Папа'),
        ),
    ]
